apiVersion: v1
kind: Service
metadata:
  labels:
    app: gocon-app
  name: gocon-app
spec:
  type: LoadBalancer
  selector:
    app: gocon-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8083
